import 'package:gyawun_metadata_sdk/metadata/interfaces/iui_service.dart';
import 'package:gyawun_metadata_sdk/metadata_plugin_sdk.dart';
import 'package:mocktail/mocktail.dart';
import 'package:test/test.dart';
import '../common/setup.dart';
import '_support/network_service.dart';
import '_support/storage_service.dart';
import '_support/ui_service.dart';

void main() async {
  group("Browse interface test", () {
    late HostEnv hostEnv;
    late IMetadataPlugin nativePlugin;
    late IMetadataPlugin evalPlugin;
    late IUIService mockUi;

    setUpAll(() async {
      mockUi = MockUiService();
      registerFallbackValue(FakeInputField());

      hostEnv = HostEnv(
        network: NetworkService(),
        storage: StorageService(),
        ui: mockUi,
      );
      nativePlugin = getNativePlugin(hostEnv);
      evalPlugin = getEvalPlugin(hostEnv);

      when(
        () => mockUi.showForm(
          title: any(named: 'title'),
          fields: any(named: 'fields'),
        ),
      ).thenAnswer(
        (_) async => {'token': 'cef34476-c3fe-4bb9-9703-026176e3ca1e'},
      );

      await nativePlugin.auth.authenticate();
      await evalPlugin.auth.authenticate();
    });

    tearDownAll(() async {
      await nativePlugin.auth.logout();
      await evalPlugin.auth.logout();
    });

    Future<void> testBrowseSections(IMetadataPlugin plugin) async {
      final sections = await plugin.browse.sections(offset: 0, limit: 5);

      expect(sections, isA<PaginatedResult<Section>>());
      expect(sections.offset, equals(0));
      expect(sections.limit, equals(5));
      expect(sections.total, equals(3));
      expect(sections.items, isNotEmpty);
      expect(sections.items.length, equals(3));

      final firstSection = sections.items[0];
      expect(firstSection.id, equals("created_for_you"));
      expect(firstSection.title, equals("Created For You"));
      expect(
        firstSection.description,
        equals(
          "Algorithmic playlists generated by ListenBrainz based on your liked songs",
        ),
      );

      final secondSection = sections.items[1];
      expect(secondSection.id, equals("top_artist_radios"));
      expect(secondSection.title, equals("Your Top Artist Radios"));

      final thirdSection = sections.items[2];
      expect(thirdSection.id, equals("mood_playlists"));
      expect(thirdSection.title, equals("Mood Playlists"));
    }

    Future<void> testBrowseSectionItems(IMetadataPlugin plugin) async {
      final page1 = await plugin.browse.sectionItems(
        "created_for_you",
        offset: 0,
        limit: 2,
      );
      expect(page1, isA<PaginatedResult<dynamic>>());
      expect(page1.items, isNotEmpty);

      final page2 = await plugin.browse.sectionItems(
        "created_for_you",
        offset: 1,
        limit: 2,
      );
      expect(page2, isA<PaginatedResult<dynamic>>());
      expect(page2.items, isNotEmpty);

      if (page1.items.length > 1 && page2.items.isNotEmpty) {
        final playlistFromPage1 = page1.items[1] as Playlist;
        final playlistFromPage2 = page2.items[0] as Playlist;
        expect(playlistFromPage2.id, equals(playlistFromPage1.id));
      }

      final radioPage1 = await plugin.browse.sectionItems(
        "top_artist_radios",
        offset: 0,
        limit: 2,
      );
      expect(radioPage1, isA<PaginatedResult<dynamic>>());
      expect(radioPage1.items, isNotEmpty);
      expect(radioPage1.items.first, isA<Playlist>());

      final radioPage2 = await plugin.browse.sectionItems(
        "top_artist_radios",
        offset: 1,
        limit: 2,
      );
      expect(radioPage2, isA<PaginatedResult<dynamic>>());
      expect(radioPage2.items, isNotEmpty);

      if (radioPage1.items.length > 1 && radioPage2.items.isNotEmpty) {
        final radioFromPage1 = radioPage1.items[1] as Playlist;
        final radioFromPage2 = radioPage2.items[0] as Playlist;

        expect(radioFromPage2.id, equals(radioFromPage1.id));
        expect(radioFromPage2.id, startsWith("radio:artist:"));
        expect(radioFromPage2.name, endsWith("Radio"));
      }

      final moodPage1 = await plugin.browse.sectionItems(
        "mood_playlists",
        offset: 0,
        limit: 2,
      );
      expect(moodPage1, isA<PaginatedResult<dynamic>>());
      expect(moodPage1.items, isNotEmpty);
      expect(moodPage1.items.first, isA<Playlist>());

      final moodPage2 = await plugin.browse.sectionItems(
        "mood_playlists",
        offset: 1,
        limit: 2,
      );
      expect(moodPage2, isA<PaginatedResult<dynamic>>());
      expect(moodPage2.items, isNotEmpty);

      if (moodPage1.items.length > 1 && moodPage2.items.isNotEmpty) {
        final moodFromPage1 = moodPage1.items[1] as Playlist;
        final moodFromPage2 = moodPage2.items[0] as Playlist;

        expect(moodFromPage2.id, equals(moodFromPage1.id));
        expect(moodFromPage2.id, startsWith("radio:tag:"));
        expect(moodFromPage2.name, endsWith("Mood"));
      }
    }

    group("Native tests", () {
      test(
        'Test browse sections',
        () async => await testBrowseSections(nativePlugin),
      );
      test(
        'Test browse section items',
        () async => await testBrowseSectionItems(nativePlugin),
      );
    });

    group("Eval tests", () {
      test(
        'Test browse sections',
        () async => await testBrowseSections(evalPlugin),
      );
      test(
        'Test browse section items',
        () async => await testBrowseSectionItems(evalPlugin),
      );
    });
  }, timeout: Timeout(Duration(minutes: 3)));
}
