import 'package:gyawun_metadata_plugin/plugin.dart';
import 'package:gyawun_metadata_plugin/segments/host_tools.dart';
import 'package:gyawun_metadata_plugin/segments/user.dart';
import 'package:gyawun_metadata_sdk/metadata/interfaces/ibrowse.dart';
import 'package:gyawun_metadata_sdk/metadata/models/pagination.dart';
import 'package:gyawun_metadata_sdk/metadata/models/section.dart';
import 'package:gyawun_metadata_sdk/metadata/models/playlist.dart';
import 'package:gyawun_metadata_sdk/metadata/models/user.dart';

class MusicbrainzBrowse extends IBrowse {
  final HostTools _host;
  final MusicbrainzUser _user;

  MusicbrainzBrowse(this._host, this._user);

  @override
  Future<PaginatedResult<Section>> sections({
    int offset = 0,
    int limit = 20,
  }) async {
    final List<Section> items = [
      Section(
        id: "created_for_you",
        title: "Created For You",
        description:
            "Algorithmic playlists generated by ListenBrainz based on your liked songs",
      ),
      Section(
        id: "top_artist_radios",
        title: "Your Top Artist Radios",
        description:
            "Dynamic recommendation radios based on your favorite artists",
      ),
      Section(
        id: "mood_playlists",
        title: "Mood Playlists",
        description: "Dynamic playlists generated based on listening moods",
      ),
    ];

    return PaginatedResult<Section>(
      items: items,
      total: items.length,
      offset: offset,
      limit: limit,
    );
  }

  @override
  Future<PaginatedResult<dynamic>> sectionItems(
    String id, {
    int offset = 0,
    int limit = 20,
  }) async {
    final List<dynamic> items = [];
    var totalCount = 0;

    final userData = await _user.me();
    var username = "listenbrainz";
    if (userData['user_id'] != null) {
      username = userData['user_id'] as String;
    }

    final headers = <String, String>{};
    if (_user.token != "") {
      headers['Authorization'] = 'Token ${_user.token}';
    }

    if (id == "created_for_you") {
      final playlistsData = await _host.fetchApi(
        baseUrl: MusicbrainzPlugin.lbUrl,
        path: "user/$username/playlists/createdfor",
        headers: headers,
      );

      final rawPlaylists = playlistsData['playlists'];
      if (rawPlaylists != null) {
        final playlistsList = List.from(rawPlaylists);
        for (final itemObj in playlistsList) {
          final Map item = itemObj as Map;
          final playlistVal = item['playlist'];
          if (playlistVal != null) {
            final Map playlist = playlistVal as Map;
            final String playlistUri = playlist['identifier'] as String;
            final parts = playlistUri.split('/');
            final playlistId = parts[parts.length - 1];
            final String title = playlist['title'] as String;

            final descVal = playlist['annotation'];
            final String desc = descVal != null ? descVal.toString() : "";

            final creatorVal = playlist['creator'];
            final String creator = creatorVal != null
                ? creatorVal.toString()
                : username;

            items.add(
              Playlist(
                id: playlistId,
                name: title,
                description: desc,
                externalUri: playlistUri,
                owner: User(
                  id: creator,
                  name: creator,
                  externalUri: "https://listenbrainz.org/user/$creator",
                  images: [],
                ),
                images: [],
              ),
            );
          }
        }
      }

      if (items.isEmpty) {
        final saved = await _user.savedPlaylists(offset: offset, limit: limit);
        return PaginatedResult<dynamic>(
          items: saved.items,
          total: saved.total,
          offset: offset,
          limit: limit,
        );
      }
    } else if (id == "top_artist_radios") {
      final statsData = await _host.fetchApi(
        baseUrl: MusicbrainzPlugin.lbUrl,
        path: "stats/user/$username/artists",
        headers: headers,
        query: {'range': 'all_time', 'count': '5'},
      );

      final payload = statsData['payload'];
      final rawArtists = payload != null ? payload['artists'] : null;

      if (rawArtists != null) {
        final artistsList = List.from(rawArtists);
        totalCount = artistsList.length;

        for (final artistObj in artistsList) {
          final Map artist = artistObj as Map;
          final artistNameVal =
              artist['artist_name'] ?? artist['artist_credit_name'];
          final String artistName = artistNameVal != null
              ? artistNameVal.toString()
              : "Unknown Artist";
          final String mbid = artist['artist_mbid'] as String;

          items.add(
            Playlist(
              id: "radio:artist:$artistName",
              name: "$artistName Radio",
              description:
                  "Algorithmic recommendation radio based on $artistName",
              externalUri: "https://listenbrainz.org/artist/$mbid",
              owner: User(
                id: "listenbrainz",
                name: "ListenBrainz",
                externalUri: "https://listenbrainz.org",
                images: [],
              ),
              images: [],
            ),
          );
        }
      }
    } else if (id == "mood_playlists") {
      final List<Map> moods = [
        {"tag": "romantic", "title": "Romantic Mood"},
        {"tag": "chill", "title": "Chill Mood"},
        {"tag": "happy", "title": "Happy Mood"},
        {"tag": "sad", "title": "Sad Mood"},
        {"tag": "focus", "title": "Focus Mood"},
      ];

      totalCount = moods.length;
      for (final moodObj in moods) {
        final String tag = moodObj['tag'] as String;
        final String title = moodObj['title'] as String;

        items.add(
          Playlist(
            id: "radio:tag:$tag",
            name: title,
            description:
                "Algorithmic recommendations generated based on the $tag mood",
            externalUri: "https://listenbrainz.org",
            owner: User(
              id: "listenbrainz",
              name: "ListenBrainz",
              externalUri: "https://listenbrainz.org",
              images: [],
            ),
            images: [],
          ),
        );
      }
    }

    final List<dynamic> pagedItems = [];
    int index = 0;
    for (final item in items) {
      if (index >= offset && index < offset + limit) {
        pagedItems.add(item);
      }
      index++;
    }

    return PaginatedResult<dynamic>(
      items: pagedItems,
      total: totalCount > 0 ? totalCount : items.length,
      offset: offset,
      limit: limit,
    );
  }
}
